name: GitHub Pages Trigger
on:
  push:
    paths: ["docs-build/**"]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🔎
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: main 
          FOLDER: docs-build
          CLEAN: true 
          TARGET_FOLDER: docs 
